/* A packrat parser generated by PackCC 1.8.0 */

#ifndef PCC_INCLUDED_HTTP_AUTH_HEADER_PARSER_H
#define PCC_INCLUDED_HTTP_AUTH_HEADER_PARSER_H

#line 10 "http_auth_header_parser.peg"
#include "sasl_header_parser.h"
#line 8 "http_auth_header_parser.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct sasl_header_context_tag sasl_header_context_t;

sasl_header_context_t *sasl_header_create(sasl_header_fields_t*auxil);
int sasl_header_parse(sasl_header_context_t *ctx, int *ret);
void sasl_header_destroy(sasl_header_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_HTTP_AUTH_HEADER_PARSER_H */
